### PR TITLE
Mention dual ESM/CJS declarations in extensionless readme and in the table

### PR DESCRIPTION
**Pull request by fictitious**

### CODE REVIEW

**Comment by andrewbranch** [comment]
Ah, I was worried this might confuse people. All three strategies support dual ESM/CJS types; I just threw in some orthogonal variation to be able to show how subpath exports compose with more features, and mentioned it [here](https://github.com/andrewbranch/example-subpath-exports-ts-compat/tree/main/examples/node_modules/package-json-redirects):

> Note that the separate handling of ESM and CJS, as well as the decision to present a unified set of types for the two, is orthogonal to the subpath exports demonstration. (Including separate types for CJS and ESM files, as [extensionless](https://github.com/andrewbranch/example-subpath-exports-ts-compat/blob/main/examples/node_modules/extensionless) does, is often a better choice, and is compatible with this strategy.)

**Comment by fictitious** [comment]
Ah yes I got confused by the presence of `"types"` in `exports` in the other two strategies. I missed that comment, and thought that `"types"` was essential there.

But, for the `types-versions-wildcards`, it looks like `"typesVersions"` takes precedence over `"exports"`, and it does not matter if the `exports` contains `types` or not. I have test code which shows that typings from `"typesVersions"` are always selected, even for ESM code with `"moduleResolution": "node16"`, and sibling lookup does not happen. Is this a bug, or my misunderstanding, and/or should it be mentioned in the READMEs somewhere?

**Comment by andrewbranch** [comment]
That sounds like it might be a bug. I’ll investigate. Thanks!

**Comment by andrewbranch** [comment]
https://github.com/microsoft/TypeScript/pull/50890

**Pull request closed without merging**
